SET SERVEROUTPUT ON
CREATE TABLE EMPLOYEE(
    EMP_ID NUMBER CONSTRAINT EMPLOYEE_PK PRIMARY KEY,
    FIRST_NAME VARCHAR2(200),
    LAST_NAME VARCHAR2(200),
    GENDER VARCHAR(10),
    PHONE VARCHAR2(200),
    ADDRESS VARCHAR2(200),
    SALARY NUMBER,
    ROLE VARCHAR2(200)
);


INSERT INTO EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, GENDER, PHONE, ADDRESS, SALARY, ROLE)
VALUES (1,'Tran Anh', 'Huy','Male', '0921231741', 'KTX khu B', 10000000,'Manager');
INSERT INTO EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, GENDER, PHONE, ADDRESS, SALARY, ROLE)
VALUES (2,'Thai Tang', 'Duc','Male', '0977164279', 'KTX khu A',5000000, 'Cashier');
INSERT INTO EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, GENDER, PHONE, ADDRESS, SALARY, ROLE)
VALUES (3,'Bui Duc', 'Duy','Male', '0356315873', '731 Tran Hung Dao, Q5, TpHCM', 5000000, 'Cashier');
INSERT INTO EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, GENDER, PHONE, ADDRESS, SALARY, ROLE)
VALUES (4,'Ton Nu Tu', 'Quyen','FeMale', '0585784600', '45 Nguyen Canh Chan, Q1, TPHCM', 5000000, 'Salesperson');
INSERT INTO EMPLOYEE (EMP_ID, FIRST_NAME, LAST_NAME, GENDER, PHONE, ADDRESS, SALARY, ROLE)
VALUES (5,'Nguyen Thi My', 'Tran','Female', '0932342312', '50/34 Le Dai Hanh, Q10, TPHCM', 5000000, 'Storekeeper');

CREATE OR REPLACE PROCEDURE deleteEmp(empid EMPLOYEE.EMP_ID%TYPE)
AS
BEGIN
    DELETE FROM EMPLOYEE WHERE EMP_ID = empid;
END;
/
BEGIN
    deleteEmp(6);
    commit;
END;

